#!/bin/bash

if [ -f "$1" ]; then
  #first arg is file
  #run docker solver on file
  docker run -v $(realpath $1):$(realpath $1) jdanner/2xornado:latest $(realpath $1) ${@:2}
else
  echo "Note: docker usage needs first argument to be fname."
  echo ""
  docker run jdanner/2xornado:latest -h
fi
